# Generated by Django 6.0 on 2025-12-20 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caisse", models.CharField(max_length=255, verbose_name="Caisse")),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "description_pannes",
                    models.TextField(blank=True, verbose_name="Description des pannes"),
                ),
                (
                    "intervention",
                    models.TextField(blank=True, verbose_name="Interventions"),
                ),
                (
                    "design_refer",
                    models.TextField(
                        blank=True, verbose_name="Designations et References"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantite")),
                (
                    "fonction",
                    models.CharField(
                        db_column="function_1", max_length=255, verbose_name="Fonction"
                    ),
                ),
                ("agent", models.CharField(max_length=255, verbose_name="Agent")),
                (
                    "Fonct",
                    models.CharField(
                        db_column="function_2", max_length=255, verbose_name="Fonction"
                    ),
                ),
                (
                    "agent_dsi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DECHARGES DES SORTIES DES MATERIELS",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caisse", models.CharField(max_length=255, verbose_name="Caisse")),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "description_pannes",
                    models.TextField(blank=True, verbose_name="Description des pannes"),
                ),
                (
                    "intervention",
                    models.TextField(blank=True, verbose_name="Interventions"),
                ),
                (
                    "design_refer",
                    models.TextField(
                        blank=True, verbose_name="Designations et References"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantite")),
                (
                    "fonction",
                    models.CharField(
                        db_column="function_3", max_length=255, verbose_name="Fonction"
                    ),
                ),
                ("agent", models.CharField(max_length=255, verbose_name="Agent")),
                (
                    "Fonct",
                    models.CharField(
                        db_column="function_4", max_length=255, verbose_name="Fonction"
                    ),
                ),
                (
                    "agent_dsi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DECHARGES DES ENTREES DES MATERIELS",
                "ordering": ["-date"],
            },
        ),
    ]
